'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ComboListBox
    
    '''<summary>
    '''pnlComboListBoxWrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlComboListBoxWrapper As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ibtnAddConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnAddConfirm As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''tdEntryCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdEntryCell As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtSourceEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSourceEntry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSourceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSourceList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tdArrowsCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdArrowsCell As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ibtnMoveUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMoveUp As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibtnMoveDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnMoveDown As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lbListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ibtnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnDelete As Global.System.Web.UI.WebControls.ImageButton
End Class
